/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.forms;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JPanel;

/**
 *
 * @author kotar
 */
public class ClientForm extends javax.swing.JFrame {

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mainPanel = new javax.swing.JPanel();
        lblPlaceholder = new javax.swing.JLabel();
        lblStudentOfficer = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInternship = new javax.swing.JMenu();
        itemInternships = new javax.swing.JMenuItem();
        menuAdministration = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        itemExamPeriod = new javax.swing.JMenuItem();
        itemTeacher = new javax.swing.JMenuItem();
        itemStudyLevel = new javax.swing.JMenuItem();
        itemStudentOfficer = new javax.swing.JMenuItem();
        itemStudent = new javax.swing.JMenuItem();
        itemCountry = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        itemHelp = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evidencija studentskih praksi");
        setResizable(false);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        lblPlaceholder.setText("Korisnik:");

        lblStudentOfficer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStudentOfficer.setText("ime i prezime");

        menuInternship.setText(" Strucna praksa");

        itemInternships.setText("Pregled strucnih praksi");
        menuInternship.add(itemInternships);

        jMenuBar1.add(menuInternship);

        menuAdministration.setText(" Administracija");

        jMenu1.setText("Fakultet");

        itemExamPeriod.setText("Ispitni rokovi");
        jMenu1.add(itemExamPeriod);

        itemTeacher.setText("Nastavnici ");
        jMenu1.add(itemTeacher);

        itemStudyLevel.setText("Nivoi studija, studijski programi, moduli");
        jMenu1.add(itemStudyLevel);

        itemStudentOfficer.setText("Sluzbenici");
        jMenu1.add(itemStudentOfficer);

        itemStudent.setText("Studenti");
        jMenu1.add(itemStudent);

        menuAdministration.add(jMenu1);

        itemCountry.setText("Drzave, gradovi");
        menuAdministration.add(itemCountry);

        jMenuBar1.add(menuAdministration);

        menuAbout.setText(" O programu");

        itemHelp.setText("Pomoc");
        menuAbout.add(itemHelp);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 833, Short.MAX_VALUE)
                        .addComponent(lblPlaceholder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStudentOfficer))
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaceholder)
                    .addComponent(lblStudentOfficer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JMenu getMenuAdministration() {
        return menuAdministration;
    }

    public JMenu getMenuInternship() {
        return menuInternship;
    }

    public JMenu getMenuAbout() {
        return menuAbout;
    }

    public JLabel getLblStudentOfficer() {
        return lblStudentOfficer;
    }

    public JLabel getLblPlaceholder() {
        return lblPlaceholder;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCountry;
    private javax.swing.JMenuItem itemExamPeriod;
    private javax.swing.JMenuItem itemHelp;
    private javax.swing.JMenuItem itemInternships;
    private javax.swing.JMenuItem itemStudent;
    private javax.swing.JMenuItem itemStudentOfficer;
    private javax.swing.JMenuItem itemStudyLevel;
    private javax.swing.JMenuItem itemTeacher;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblPlaceholder;
    private javax.swing.JLabel lblStudentOfficer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuAdministration;
    private javax.swing.JMenu menuInternship;
    // End of variables declaration//GEN-END:variables

    public void showCountriesAddActionListener(ActionListener actionListener) {
        itemCountry.addActionListener(actionListener);
    }

    public void showExamPeriodsAddActionListener(ActionListener actionListener) {
        itemExamPeriod.addActionListener(actionListener);
    }

    public void showTeachersAddActionListener(ActionListener actionListener) {
        itemTeacher.addActionListener(actionListener);
    }

    public void showStudyLevelsAddActionListener(ActionListener actionListener) {
        itemStudyLevel.addActionListener(actionListener);
    }

    public void showInternshipsAddActionListener(ActionListener actionListener) {
        itemInternships.addActionListener(actionListener);
    }

    public void showStudentOfficersAddActionListener(ActionListener actionListener) {
        itemStudentOfficer.addActionListener(actionListener);
    }

    public void showStudentsAddActionListener(ActionListener actionListener) {
        itemStudent.addActionListener(actionListener);
    }

    public void showHelpAddActionListener(ActionListener actionListener) {
        itemHelp.addActionListener(actionListener);
    }

}
