/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author kotar
 */
public class ClientForm extends javax.swing.JFrame {

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mainPanel = new javax.swing.JPanel();
        lblPlaceholder = new javax.swing.JLabel();
        lblStudentOfficer = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuReports = new javax.swing.JMenu();
        itemAddReport = new javax.swing.JMenuItem();
        itemShowReports = new javax.swing.JMenuItem();
        menuCountry = new javax.swing.JMenu();
        itemAddCountry = new javax.swing.JMenuItem();
        itemShowCountries = new javax.swing.JMenuItem();
        menuExamPeriods = new javax.swing.JMenu();
        itemAddExamPeriod = new javax.swing.JMenuItem();
        itemShowExamPeriods = new javax.swing.JMenuItem();
        menuTeacher = new javax.swing.JMenu();
        itemAddTeacher = new javax.swing.JMenuItem();
        itemShowTeachers = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        lblPlaceholder.setText("Korisnik:");

        lblStudentOfficer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStudentOfficer.setText("ime i prezime");

        menu.setText("Administracija sifarnika");

        menuReports.setText("Dnevnik prakse");

        itemAddReport.setText("Kreiraj dnevnik prakse");
        menuReports.add(itemAddReport);

        itemShowReports.setText("Prikaz dnevnika prakse");
        menuReports.add(itemShowReports);

        menu.add(menuReports);

        menuCountry.setText("Drzava");

        itemAddCountry.setText("Kreiraj drzavu");
        menuCountry.add(itemAddCountry);

        itemShowCountries.setText("Prikaz drzava");
        menuCountry.add(itemShowCountries);

        menu.add(menuCountry);

        menuExamPeriods.setText("Ispitni rok");

        itemAddExamPeriod.setText("Kreiraj ispitni rok");
        menuExamPeriods.add(itemAddExamPeriod);

        itemShowExamPeriods.setText("Prikaz ispitnih rokova");
        menuExamPeriods.add(itemShowExamPeriods);

        menu.add(menuExamPeriods);

        menuTeacher.setText("Nastavnik");

        itemAddTeacher.setText("Dodaj nastavnika");
        menuTeacher.add(itemAddTeacher);

        itemShowTeachers.setText("Prikaz nastavnika");
        menuTeacher.add(itemShowTeachers);

        menu.add(menuTeacher);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 522, Short.MAX_VALUE)
                        .addComponent(lblPlaceholder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStudentOfficer)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaceholder)
                    .addComponent(lblStudentOfficer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JMenu getMenu() {
        return menu;
    }

    public JLabel getLblStudentOfficer() {
        return lblStudentOfficer;
    }

    public JLabel getLblPlaceholder() {
        return lblPlaceholder;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAddCountry;
    private javax.swing.JMenuItem itemAddExamPeriod;
    private javax.swing.JMenuItem itemAddReport;
    private javax.swing.JMenuItem itemAddTeacher;
    private javax.swing.JMenuItem itemShowCountries;
    private javax.swing.JMenuItem itemShowExamPeriods;
    private javax.swing.JMenuItem itemShowReports;
    private javax.swing.JMenuItem itemShowTeachers;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblPlaceholder;
    private javax.swing.JLabel lblStudentOfficer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu menuCountry;
    private javax.swing.JMenu menuExamPeriods;
    private javax.swing.JMenu menuReports;
    private javax.swing.JMenu menuTeacher;
    // End of variables declaration//GEN-END:variables

    public void addReportAddActionListener(ActionListener actionListener) {
        itemAddReport.addActionListener(actionListener);
    }

    public void showReportsAddActionListener(ActionListener actionListener) {
        itemShowReports.addActionListener(actionListener);
    }

    public void addCountryAddActionListener(ActionListener actionListener) {
        itemAddCountry.addActionListener(actionListener);
    }

    public void showCountriesAddActionListener(ActionListener actionListener) {
        itemShowCountries.addActionListener(actionListener);
    }

    public void addExamPeriodAddActionListener(ActionListener actionListener) {
        itemAddExamPeriod.addActionListener(actionListener);
    }

    public void showExamPeriodsAddActionListener(ActionListener actionListener) {
        itemShowExamPeriods.addActionListener(actionListener);
    }

    public void addTeacherAddActionListener(ActionListener actionListener) {
        itemAddTeacher.addActionListener(actionListener);
    }

    public void showTeachersAddActionListener(ActionListener actionListener) {
        itemShowTeachers.addActionListener(actionListener);
    }
}
