/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author kotar
 */
public class ClientForm extends javax.swing.JFrame {

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mainPanel = new javax.swing.JPanel();
        lblPlaceholder = new javax.swing.JLabel();
        lblStudentOfficer = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        itemReport = new javax.swing.JMenuItem();
        itemCountry = new javax.swing.JMenuItem();
        itemExamPeriod = new javax.swing.JMenuItem();
        itemTeacher = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evidencija studentskih praksi");
        setResizable(false);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        lblPlaceholder.setText("Korisnik:");

        lblStudentOfficer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStudentOfficer.setText("ime i prezime");

        menu.setText("Administracija sifarnika");

        itemReport.setText("Dnevnik prakse");
        menu.add(itemReport);

        itemCountry.setText("Drzava");
        menu.add(itemCountry);

        itemExamPeriod.setText("Ispitni rok");
        menu.add(itemExamPeriod);

        itemTeacher.setText("Nastavnik");
        menu.add(itemTeacher);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 522, Short.MAX_VALUE)
                        .addComponent(lblPlaceholder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStudentOfficer))
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaceholder)
                    .addComponent(lblStudentOfficer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JMenu getMenu() {
        return menu;
    }

    public JLabel getLblStudentOfficer() {
        return lblStudentOfficer;
    }

    public JLabel getLblPlaceholder() {
        return lblPlaceholder;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCountry;
    private javax.swing.JMenuItem itemExamPeriod;
    private javax.swing.JMenuItem itemReport;
    private javax.swing.JMenuItem itemTeacher;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblPlaceholder;
    private javax.swing.JLabel lblStudentOfficer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menu;
    // End of variables declaration//GEN-END:variables

    public void showReportsAddActionListener(ActionListener actionListener) {
        itemReport.addActionListener(actionListener);
    }

    public void showCountriesAddActionListener(ActionListener actionListener) {
        itemCountry.addActionListener(actionListener);
    }

    public void showExamPeriodsAddActionListener(ActionListener actionListener) {
        itemExamPeriod.addActionListener(actionListener);
    }

    public void showTeachersAddActionListener(ActionListener actionListener) {
        itemTeacher.addActionListener(actionListener);
    }

}
